### PR TITLE
Add warning to README

### PR DESCRIPTION
**Pull request by DonRichards**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1842

Parent ticket https://jira.duraspace.org/browse/ISLANDORA-1260

# What does this Pull Request do?

Informs the user removing/deleting a newspaper will also delete and child issues and pages associated with it. 

# What's new?
diagram image. 

# How should this be tested?
N/A

# Additional Notes:
N/A

# Interested parties
@whikloj @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by whikloj** [comment]
@DonRichards I just tried this and if I go to **Manage** -> **Properties** -> **Delete newspaper**.

I see this warning.

delete_newspaper


So I'm unsure that this is needed or if it needs to be so prominent?

**Comment by DonRichards** [comment]
The ticket had 2 parts; at the code level and in the documentation. The code update was done a while back but the documentation wasn't. This was some house cleaning I guess. We can close this if it's too redundant.

**Comment by whikloj** [comment]
Oh okay, then could we change the first sentence from 
> Deleting a newspaper object will invariantly delete all its child issue objects, and their associated page objects without warning.

to

> Deleting a newspaper object will delete all its child issue objects, and their associated page objects.

I'm not sure that the word _invariantly_ doesn't make the sentence overly complex. For the ending there is a warning displayed, if people fail to read it that would be user error.

**Comment by DiegoPino** [comment]
We could add 💣 emoticon to make it clear 😄  
Joke by side, do we use the word "purge" and "delete" as synonyms. Wonder since we do have the "deleted" state around in islandora which is not really a delete.I agree with @whikloj that _invariantly_ could lead to people thinking other deletes are not.. but i agree also that documentation was needed.

**Comment by DonRichards** [comment]
Yeah. Good point. @DiegoPino does it purge?

**Comment by DiegoPino** [comment]
@DonRichards it actually does purge. It seems like the issue with that is how we have been using delete and purge all over the place as the same stuff. Which also makes sense because delete is what people know better and purge more a repository based term, but we need disambiguation probably from now on (and specially thinking about the future with CLAW) where "delete" could be on drupal side and purge drupal and fedora. So maybe a question for a committer call or for you both, whatever makes you more comfortable. I just wish for uniformity if we are giving people messages like this also in books and collections?

**Comment by DonRichards** [comment]
Should I change the word deleted to 'purged'? That's a quick fix.

**Comment by DiegoPino** [comment]
@whikloj?

**Comment by whikloj** [comment]
In 1.x there is no difference between delete and purge, so I think deleted is fine. 

People understand delete and will have to be educated about purge. Might as well leave that for now.

**Comment by DonRichards** [comment]
Great.

**Comment by rosiel** [comment]
Can we take a couple of questions to the Documentation Interest Group?
* How should we refer to the step of deleting (purging) an object to make it unambiguous that we are actually making it gone gone, not just setting it to the state deleted, while also easily understandable to a non-expert?
* In all our README.md's we say "For more information see the wiki" and link to this module's wiki page. In almost all cases, the wiki contains no further information. Should we perhaps flesh out how we use the wiki vs the readme, and could explanations of common 'gotchas' be a use case for the wiki over the readme (I'm not saying we shouldn't accept this PR - I think it's a good improvement to our documentation - but it spawns a bigger potential improvement on how we document.)

**Comment by DonRichards** [comment]
And now we finally have a topic to start the interest group back up. Thanks @rosiel

**Comment by bondjimbond** [comment]
@rosiel @DiegoPino @DonRichards 

Something important to note (which I consider a major bug): I'm not sure that this warning is actually accurate in the first place. I've noticed a TON of orphaned objects after building the [Orphaned Objects module](https://github.com/bondjimbond/islandora_orphaned_objects), most of which were newspaper pages.

Today in my Vagrant machine I tried deleting a newspaper (via the Properties page) to see whether deleting all the pages etc actually happened. It didn't.

The progress bar claimed that all these pages were being deleted, and I even got notification from a different test module that all these pages had been modified - but when I looked at the Orphaned Objects list, it turns out that the pages were actually still in the repository, active and accessible, but with no parent.

I suspect that by deleting a Newspaper deletes its Issues, but the chain stops there - it doesn't go further and delete the Pages.

**Comment by DiegoPino** [comment]
@bondjimbond, in that case, let's fix that first. Could you see if we already have a JIRA ticket for that issue? If not open one and we can move from there. Good timing to get that finally done. (Don't be surprised if any of us were assigned in the past to that ticket, probably me!) This leaves this pull in standby until solved

**Comment by bondjimbond** [comment]
@DiegoPino Apparently there wasn't an issue specifically about this, though I did submit another orphan object issue a while back. Here's a new one:

https://jira.duraspace.org/browse/ISLANDORA-2050

Given that the usual methods of deleting newspapers and newspaper issues do not work as planned, I'm very curious about how many repositories have large numbers of orphaned objects that they don't know about. I was pretty shocked when I ran the module on my relatively young multisite and found over 7,000 orphans.

**Comment by DiegoPino** [comment]
@bondjimbond not sure really but I guess many institutions without someone to develop solutions for them. Good. This is a nice tasks for this weekened ;) Will give it a shot

**Comment by bondjimbond** [comment]
Sorry @DiegoPino - I gave the wrong JIRA link. This is the one dealing with Newspapers: https://jira.duraspace.org/browse/ISLANDORA-2065

**Comment by DiegoPino** [comment]
@bondjimbond to what issue I assigned myself then? 😆

**Comment by DiegoPino** [comment]
@bondjimbond does this affect book also?

**Comment by bondjimbond** [comment]
@DiegoPino Both issues are relevant, so I'd be happy if you tackled them both. 😁 

Deleting a book via its Properties tab: works as expected - children deleted. ISLANDORA-2065 not applicable.

Deleting a book via the Collection management screen: children orphaned. ISLANDORA-2050 applies.

**Comment by DiegoPino** [comment]
aha! Ok, that just got me an idea. maybe each SP that has compounds should register a hook that tells collection sp how to handle deletion? Will give that a try
thanks!

**Comment by manez** [comment]
I took over Documentation for this module for 7.x-1.10, so just checking in on this. **Anyone object to merging the addition as it is?** The separate issue where sometimes _this doesn't work_ is a bug, documented in [JIRA](https://jira.duraspace.org/browse/ISLANDORA-2065), and being worked on, so even if it doesn't get fixed for 7.x-1.10 is will be documented via release notes. Will seek a release pull if this goes in.

Starting a 24-hour clock on merging, so speak up 😄

**Review by manez — APPROVED** [review]

**Comment by DiegoPino** [comment]
+1 from me to merging

**Comment by manez** [comment]
ok... after the release call: holding off on this one until we see what happens with the bug fix. May need to fix the UI documentation to tell the truth instead of adding this so we lie consistently 😉

**Comment by bondjimbond** [comment]
+1 to not lying

**Review by rosiel — CHANGES_REQUESTED** [review]
This is not accurate. I did a thorough analysis with four newspapers and deleted things in various ways to see what happened. I have a video, i'll post it shortly. But I think this needs revision because it is not accurate either. Sometimes orphans are not created.

**Comment by rosiel** [comment]
Here's the video of deleting stuff. With a super action soundtrack for your viewing pleasure.
https://www.dropbox.com/s/fjbzjv6olmsnjyj/islandora-deleting-a-newspaper-7.x-1.10RC2.mp4?dl=0

Summary:

1. If you delete the newspaper object from its own properties tab: all issues and pages are deleted, as desired. This is the screen in @whikloj 's [comment](https://github.com/Islandora/islandora_solution_pack_newspaper/pull/153#issuecomment-330909650) above. From this perspective, things are working a-ok and the warning, as articulated [here](https://github.com/Islandora/islandora_solution_pack_newspaper/pull/153/commits/c6edb97caee5b5cf7f333b29549d97723a61a1f3), is accurate. 

2. If you go to the newspaper's parent collection, and in the "Delete members of this collection" interface you delete the newspaper, then issues and pages remain. (the issues are orphans; the pages are children of orphans but not orphans themselves).

3. If you delete the newspaper's parent collection altogether, on the parent collection's Properties tab, then the newspaper (the direct child of the collection) gets deleted but the issues and pages remain (and the issues are orphans, as above).

@bondjimbond described this in his [ticket](https://jira.duraspace.org/browse/ISLANDORA-2050) about collection-initiated deletes failing to cascade. 

Perhaps the wording of this warning could be changed to:
```
:warning: <br/>Deleting a newspaper object directly (Manage > Properties >  Delete Newspaper)
 will delete all its child Issue objects, and their associated Page objects. Highlighted in red in this
 diagram shows all that will be deleted if the newspaper Locusta Newspaper is deleted. 

However, there is a known but when deleting a newspaper via its parent collection (by deleting the
 collection or by using "Delete members of this collection") will cause that newspaper's Issue 
objects to be orphaned.
```

**Comment by manez** [comment]
Since I signed up to Document this for the release and we're down to our last hours, I made a pull request to roll this together with @rosiel 's suggestion, so we correctly describe the behaviour. #154

**Comment by rosiel** [comment]
Closing, as to get this in the release in time, it was incorporated in #154 and #155.

**Pull request closed without merging**
