### PR TITLE
Clearing up hook naming changes.

### PR DESCRIPTION
**Pull request by knjackson30974**
**Jira:** https://jira.duraspace.org/browse/ISLANDORA-1637
# What does this Pull Request do?

Addresses hook naming changes in xml_form_builder. 
# How should this be tested?

Check that hook names match hook names in xml_form_builder.api.php
# Background context:
# Additional Notes:
- **Does this change require documentation to be updated?** No.
- **Does this change add any new dependencies?** No.
- **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No.
- **Could this change impact execution of existing code?** If any implementations of the hooks were missed perhaps. Would be minor. 

**Tagging:** Will tag on islandora_xml_forms to keep things less redundant. 

---

Kylea Jackson

_Developer_

**[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content**

### CODE REVIEW

**Comment by whikloj** [comment]
This PR depends on https://github.com/Islandora/islandora_xml_forms/pull/221

**Comment by dannylamb** [comment]
Re-running tests on this to make sure it wasn't just a hiccup.

**Comment by dannylamb** [comment]
These tests are failing using islandora-vagrant and on Travis.  The 7.x branch is passing on Travis, but locally I'm getting the same errors on 7.x.  Not sure what to trust at this point.

**Comment by dannylamb** [comment]
@Islandora/7-x-1-x-committers Can anyone else confirm or deny these test failures. I'd really like to get these in before the freeze.

@knjackson30974 can you run tests on a dgi environment for me?

**Review by DiegoPino — APPROVED** [review]
Part of a 13 piece set. Restarted Travis (had failed, corrected via OCR fix from a few months ago) and success. Tested and works with XML forms #221 pull merged. Merging now

**Pull request merged**
