### PR TITLE
updated issue query so it works better with xacml see jira islandora-118...

### PR DESCRIPTION
**Pull request by ppound**
...1

### CODE REVIEW

**Comment by ppound** [comment]
It addresses jira ticket islandora-1181 which we have listed as a major bug.  

I'll have to do another pull request for the release branch.

**Comment by whikloj** [comment]
I think I understand now. 

I was confused because **dateIssued** came in on 2013-03-27 but **sequence** was made optional [2013-04-01](https://github.com/Islandora/islandora_solution_pack_newspaper/commit/2d6c1e01cc146a6a94f19174344e8667e8fcf609#diff-2d69368f59ba81d5635cd8274dd66090R77) and sort order was switched to by **dateIssued** [the same day](https://github.com/Islandora/islandora_solution_pack_newspaper/commit/6f4c451d3a3ad44560cd6197cd0945e76d5e1883#diff-2d69368f59ba81d5635cd8274dd66090R82). 

Then it was switched back to the current state on [2013-10-16](https://github.com/Islandora/islandora_solution_pack_newspaper/commit/cb21502df746c7b64fc3cbc2638d5e48ef384c82). 

I think we added our first bunch of our newspapers in that gap.

**Comment by ppound** [comment]
We discussed post processing as option for this, I'm thinking post processing will make an already slow loading page slower.  We already have a ticket regarding slow issue page loads (https://jira.duraspace.org/browse/ISLANDORA-1167) so maybe we can close this pull request and look at other options like using solr.

Another thing we may want to address when moving to solr is our current practice of iterating over the list of issues and giving the incorrect date to issues that do not currently have a dateIssued (https://github.com/Islandora/islandora_solution_pack_newspaper/blob/7.x/includes/utilities.inc#L116-L135).

**Comment by whikloj** [comment]
This is waiting on https://github.com/Islandora/islandora_solution_pack_newspaper/pull/120

**Pull request merged**
