### PR TITLE
Update README maintainer

### PR DESCRIPTION
**Pull request by librarychik**
# What's new?

Changed maintainer
# How should this be tested?

no testing 
# Interested parties

@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@librarychik hi, it's github.com/DiegoPino, do you want me to pull against your pull or it's faster if you fix it? thanks 😄

**Comment by librarychik** [comment]
@DiegoPino Oh, sorry :(  I'll fix

**Comment by librarychik** [comment]
@DiegoPino let me know if I fixed it properly (still a newbie)

**Comment by DiegoPino** [comment]
@librarychik thanks! Perfect fix.

**Pull request merged**
